import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest'
import ProjectCommercial, { businessFileError, validateAllocations } from '../project/ProjectCommercial'
import { contract, installProjectDom, page, projectRepository } from './project-fixtures'

beforeAll(installProjectDom)
afterEach(() => { cleanup(); vi.restoreAllMocks() })
describe('React 商务与收款', () => {
  it('多项目分摊以分校验，拒绝总额不一致、重复与漏掉当前项目', () => {
    expect(validateAllocations([{ project_code: 'A', amount: '0.10' }, { project_code: 'B', amount: '0.20' }], 30, 'A')).toEqual([{ project_code: 'A', amount_cents: 10 }, { project_code: 'B', amount_cents: 20 }])
    expect(() => validateAllocations([{ project_code: 'A', amount: '1.00' }], 101, 'A')).toThrow('之和')
    expect(() => validateAllocations([{ project_code: 'A', amount: '1' }, { project_code: 'A', amount: '1' }], 200, 'A')).toThrow('一次')
    expect(() => validateAllocations([{ project_code: 'B', amount: '1' }], 100, 'A')).toThrow('当前项目')
  })
  it('编辑报价将元金额转成分，保留原附件与 revision', async () => {
    const repository = projectRepository()
    render(<ProjectCommercial projectCode="SY-A" repository={repository} />)
    fireEvent.click(await screen.findByRole('button', { name: /编\s*辑$/ }))
    const dialog = await screen.findByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('报价金额'), { target: { value: '321.09' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /保\s*存$/ }))
    await waitFor(() => expect(repository.updateQuote).toHaveBeenCalledWith('SY-A', 10, expect.objectContaining({ amount_cents: 32109, expected_revision: 3, document_version_ids: [22] })))
  })
  it('编辑合同保留多项目分摊，支持正常提交', async () => {
    const repository = projectRepository()
    vi.mocked(repository.listContracts).mockResolvedValue(page([{ ...contract, status: 'draft' }]))
    render(<ProjectCommercial projectCode="SY-A" repository={repository} />)
    await screen.findByRole('button', { name: /编\s*辑$/ })
    fireEvent.click(screen.getByRole('tab', { name: '项目合同 (1)' }))
    fireEvent.click(await screen.findByRole('button', { name: /编\s*辑$/ }))
    const dialog = await screen.findByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('合同名称'), { target: { value: '设备安装合同修订' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /保\s*存$/ }))
    await waitFor(() => expect(repository.updateContract).toHaveBeenCalledWith('SY-A', 1, expect.objectContaining({ title: '设备安装合同修订', allocations: [{ project_code: 'SY-A', amount_cents: 60000 }, { project_code: 'SY-B', amount_cents: 40000 }], expected_revision: 2 })))
  })
  it('到账说明更新不会改写金额归属，作废要求明确原因与版本', async () => {
    const repository = projectRepository()
    render(<ProjectCommercial projectCode="SY-A" repository={repository} />)
    await screen.findByRole('button', { name: /编\s*辑$/ })
    fireEvent.click(screen.getByRole('tab', { name: '收款与到账' }))
    fireEvent.click(await screen.findByRole('button', { name: /说\s*明$/ }))
    let dialog = await screen.findByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('参考号'), { target: { value: 'BANK2' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /保\s*存$/ }))
    await waitFor(() => expect(repository.updateReceipt).toHaveBeenCalledWith('SY-A', 5, { reference_no: 'BANK2', notes: null, expected_revision: 6 }))
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    fireEvent.click(await screen.findByRole('button', { name: /作\s*废$/ }))
    dialog = await screen.findByRole('dialog')
    fireEvent.click(within(dialog).getByRole('button', { name: '确认作废' }))
    await within(dialog).findByText('请填写作废原因')
    expect(repository.voidReceipt).not.toHaveBeenCalled()
    fireEvent.change(within(dialog).getByLabelText('作废原因'), { target: { value: '银行流水重复录入' } })
    fireEvent.click(within(dialog).getByRole('button', { name: '确认作废' }))
    await waitFor(() => expect(repository.voidReceipt).toHaveBeenCalledWith('SY-A', 5, expect.objectContaining({ reason: '银行流水重复录入', expected_revision: 6 })))
  })
  it('报价与合同附件分别遵循原格式限制，二十一份附件不能进入待提交列表', async () => {
    expect(businessFileError(new File(['x'], '报价.xlsx'), 'quote')).toBeNull()
    expect(businessFileError(new File(['x'], '合同.xlsx'), 'contract')).toContain('格式不支持')
    expect(businessFileError(new File(['x'], '合同.pdf'), 'contract')).toBeNull()
    const repository = projectRepository()
    render(<ProjectCommercial projectCode="SY-LIMIT" repository={repository} />)
    await screen.findByRole('button', { name: /编\s*辑$/ })
    fireEvent.click(screen.getByRole('button', { name: /新增报价/ }))
    const dialog = await screen.findByRole('dialog')
    const files = Array.from({ length: 21 }, (_, index) => new File(['x'], `${index}.pdf`, { type: 'application/pdf' }))
    fireEvent.change(dialog.querySelector('input[type="file"]')!, { target: { files } })
    await within(dialog).findByText('一次最多上传 20 个附件，请先移除不需要的文件')
    expect(dialog.querySelectorAll('.ant-upload-list-item')).toHaveLength(0)
    expect(repository.createQuote).not.toHaveBeenCalled()
  })
  it('归档商务页面禁用报价、合同和到账操作', async () => {
    const repository = projectRepository()
    render(<ProjectCommercial projectCode="SY-ARCHIVED" readonly repository={repository} />)
    await screen.findByRole('button', { name: /编\s*辑$/ })
    expect((screen.getByRole('button', { name: /新增报价/ }) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.click(screen.getByRole('tab', { name: '收款与到账' }))
    expect((await screen.findByRole('button', { name: /登记到账/ }) as HTMLButtonElement).disabled).toBe(true)
    expect((screen.getByRole('button', { name: /作\s*废$/ }) as HTMLButtonElement).disabled).toBe(true)
  })

  it('合同分摊实时提示剩余金额，当前项目不会被误删', async () => {
    const repository = projectRepository()
    render(<ProjectCommercial projectCode="SY-A" repository={repository} />)
    await screen.findByRole('button', { name: /编\s*辑$/ })
    fireEvent.click(screen.getByRole('tab', { name: '项目合同 (1)' }))
    fireEvent.click(screen.getByRole('button', { name: /新增合同/ }))
    const dialog = await screen.findByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('合同总额'), { target: { value: '1000' } })
    await within(dialog).findByText('待分摊 ¥1,000.00')
    expect(within(dialog).getByRole('button', { name: '移除分摊 1' })).toHaveProperty('disabled', true)
    fireEvent.click(within(dialog).getByRole('button', { name: '将剩余 ¥1,000.00 分配到此项目' }))
    await within(dialog).findByText('分摊已平衡')
    expect(within(dialog).getByLabelText('分摊金额 1')).toHaveProperty('value', '1000.00')
    fireEvent.change(within(dialog).getByLabelText('分摊金额 1'), { target: { value: '1001' } })
    await within(dialog).findByText('超出 ¥1.00')
    expect(repository.createContract).not.toHaveBeenCalled()
  })
  it('从收款节点登记时自动带入该节点，并展示合同剩余金额', async () => {
    const repository = projectRepository()
    render(<ProjectCommercial projectCode="SY-A" repository={repository} />)
    await screen.findByRole('button', { name: /编\s*辑$/ })
    fireEvent.click(screen.getByRole('tab', { name: '收款与到账' }))
    fireEvent.click(screen.getByRole('button', { name: '登记进度款' }))
    const dialog = await screen.findByRole('dialog')
    await within(dialog).findByText('尚未到账 ¥500.00')
    fireEvent.change(within(dialog).getByLabelText('到账金额'), { target: { value: '100' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /保\s*存$/ }))
    await waitFor(() => expect(repository.createReceipt).toHaveBeenCalledWith('SY-A', expect.objectContaining({ contract_allocation_id: 11, milestone: 'progress', amount_cents: 10000 })))
  })

})
