import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import InventoryWorkspace from '../inventory/InventoryWorkspace'
import type { InventoryHttpRepository } from '../../repositories/inventory.live'

beforeAll(() => {
  Object.defineProperty(window, 'matchMedia', { writable: true, value: () => ({ matches: false, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {}, dispatchEvent() { return true } }) })
  globalThis.ResizeObserver = class { observe() {} unobserve() {} disconnect() {} }
  const original = window.getComputedStyle.bind(window)
  window.getComputedStyle = (element) => original(element)
})
afterEach(cleanup)
const item = { id: 1, name: '网线', brand: null, model: 'CAT6', specification: null, unit: '米', quantity: '12.000', average_unit_cost_cents: 300, inventory_value_cents: 3600, notes: null, revision: 2, created_at: '', updated_at: '' }
function repository() {
  return { listInventoryItems: vi.fn(async () => ({ source: 'live', data: { items: [item], page: 1, page_size: 20, total: 1 } })), createInventoryItem: vi.fn(async () => ({ source: 'live', data: item })), discardCreateInventoryItem: vi.fn(() => true) } as unknown as InventoryHttpRepository
}
describe('React 库存工作区', () => {
  it('清空搜索立即重新读取全部匹配范围，不遗留上一关键词过滤', async () => {
    const repo = repository()
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByRole('button', { name: '网线' })
    const search = screen.getByPlaceholderText('搜索品牌、名称、型号')
    fireEvent.change(search, { target: { value: 'CAT6' } })
    fireEvent.click(screen.getByRole('button', { name: /查.*询/ }))
    await waitFor(() => expect(repo.listInventoryItems).toHaveBeenLastCalledWith(expect.objectContaining({ query: 'CAT6' })))
    fireEvent.change(search, { target: { value: '' } })
    await waitFor(() => expect(repo.listInventoryItems).toHaveBeenLastCalledWith({ page: 1, page_size: 20, status: 'all' }))
    expect(screen.queryByText('关键词：CAT6')).toBeNull()
  })

  it('已应用的关键词和状态有标签，一次清除恢复全部库存', async () => {
    const repo = repository()
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByRole('button', { name: '网线' })
    fireEvent.change(screen.getByPlaceholderText('搜索品牌、名称、型号'), { target: { value: 'CAT6' } })
    fireEvent.click(screen.getByRole('button', { name: /查.*询/ }))
    fireEvent.mouseDown(screen.getByRole('combobox', { name: '库存状态' }))
    fireEvent.click(await screen.findByText('有库存'))
    await waitFor(() => expect(repo.listInventoryItems).toHaveBeenLastCalledWith({ page: 1, page_size: 20, status: 'in_stock', query: 'CAT6' }))
    expect(screen.getByText('关键词：CAT6')).toBeTruthy()
    expect(screen.getByText('状态：有库存')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: '清除筛选' }))
    await waitFor(() => expect(repo.listInventoryItems).toHaveBeenLastCalledWith({ page: 1, page_size: 20, status: 'all' }))
    expect((screen.getByPlaceholderText('搜索品牌、名称、型号') as HTMLInputElement).value).toBe('')
    expect(screen.queryByText('关键词：CAT6')).toBeNull()
    expect(screen.queryByText('状态：有库存')).toBeNull()
  })

  it('领用显示所选物料可用量，项目必须主动选择后才能提交', async () => {
    const repo = repository()
    repo.listIssueProjects = async () => ({ source: 'live', data: [{ project_code: 'SY-001', name: '现场改造' }] })
    repo.listProjectIssueWorkers = vi.fn<InventoryHttpRepository['listProjectIssueWorkers']>(async () => ({ source: 'live', data: [{ worker_id: 4, name: '张工', role: '电工' }] }))
    repo.createProjectInventoryIssue = vi.fn<InventoryHttpRepository['createProjectInventoryIssue']>(async (_code, input) => ({ source: 'live', data: { ...input, id: 3, project_id: 1, status: 'active', total_cost_cents: 600, revision: 1, lines: input.lines.map((line) => ({ ...line, id: 1, cost_cents: 600, movement_id: 1 })), created_at: '', updated_at: '' } }))
    repo.discardCreateProjectInventoryIssue = () => true
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByRole('button', { name: '网线' })
    fireEvent.click(screen.getByRole('button', { name: '项目领用' }))
    const dialog = await screen.findByRole('dialog')
    expect(within(dialog).getByRole('heading', { name: '领用去向' })).toBeTruthy()
    expect(within(dialog).getByText('可用 12.000 米')).toBeTruthy()
    expect((within(dialog).getByLabelText('项目施工员') as HTMLInputElement).disabled).toBe(true)
    fireEvent.change(within(dialog).getByLabelText('领用数量'), { target: { value: '2.000' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /^保\s*存$/ }))
    await within(dialog).findByText('请选择领用项目')
    expect(repo.createProjectInventoryIssue).not.toHaveBeenCalled()
    fireEvent.mouseDown(within(dialog).getByLabelText('领用项目'))
    fireEvent.click(await screen.findByText('现场改造 · SY-001'))
    await waitFor(() => expect(repo.listProjectIssueWorkers).toHaveBeenCalledWith('SY-001'))
    fireEvent.click(within(dialog).getByRole('button', { name: /^保\s*存$/ }))
    await waitFor(() => expect(repo.createProjectInventoryIssue).toHaveBeenCalledWith('SY-001', expect.objectContaining({ worker_id: null, lines: [{ inventory_item_id: 1, procurement_line_id: null, quantity: '2.000' }] })))
  })

  it('列表读取失败后可原地重试恢复，不把错误当空库存', async () => {
    const repo = repository()
    vi.mocked(repo.listInventoryItems).mockRejectedValueOnce(new Error('库存服务暂时不可用'))
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByText('库存服务暂时不可用')
    fireEvent.click(screen.getByRole('button', { name: '重新读取' }))
    await screen.findByRole('button', { name: '网线' })
    expect(screen.queryByText('库存服务暂时不可用')).toBeNull()
  })
  it('施工员读取失败可重试当前项目，不要求重新选择项目', async () => {
    const repo = repository()
    repo.listIssueProjects = async () => ({ source: 'live', data: [{ project_code: 'SY-001', name: '现场改造' }] })
    repo.listProjectIssueWorkers = vi.fn<InventoryHttpRepository['listProjectIssueWorkers']>()
      .mockRejectedValueOnce(new Error('施工员读取失败'))
      .mockResolvedValue({ source: 'live', data: [{ worker_id: 4, name: '张工', role: '电工' }] })
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByRole('button', { name: '网线' })
    fireEvent.click(screen.getByRole('button', { name: '项目领用' }))
    const dialog = await screen.findByRole('dialog')
    fireEvent.mouseDown(within(dialog).getByLabelText('领用项目'))
    fireEvent.click(await screen.findByText('现场改造 · SY-001'))
    await within(dialog).findByText('施工员读取失败')
    fireEvent.click(within(dialog).getByRole('button', { name: '重新读取选项' }))
    await waitFor(() => expect(repo.listProjectIssueWorkers).toHaveBeenCalledTimes(2))
    expect(repo.listProjectIssueWorkers).toHaveBeenLastCalledWith('SY-001')
    fireEvent.mouseDown(within(dialog).getByLabelText('项目施工员'))
    expect(await screen.findByText('张工 · 电工')).toBeTruthy()
    expect(within(dialog).queryByText('施工员读取失败')).toBeNull()
  })
  it('切换 repository 后忽略旧库存列表的迟到结果', async () => {
    const old = repository()
    const next = repository()
    let resolve!: (value: Awaited<ReturnType<InventoryHttpRepository['listInventoryItems']>>) => void
    old.listInventoryItems = () => new Promise((done) => { resolve = done })
    const view = render(<InventoryWorkspace repository={old} />)
    view.rerender(<InventoryWorkspace repository={next} />)
    await screen.findByRole('button', { name: '网线' })
    await act(async () => resolve({ source: 'live', data: { items: [{ ...item, name: '旧仓储物料' }], total: 1, page: 1, page_size: 20 } }))
    expect(screen.queryByRole('button', { name: '旧仓储物料' })).toBeNull()
    expect(screen.getByRole('button', { name: '网线' })).toBeTruthy()
  })
  it('显示服务端库存并通过查询控件发送检索条件', async () => {
    const repo = repository()
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByRole('button', { name: '网线' })
    fireEvent.change(screen.getByPlaceholderText('搜索品牌、名称、型号'), { target: { value: 'CAT6' } })
    fireEvent.click(screen.getByRole('button', { name: /查.*询/ }))
    await waitFor(() => expect(repo.listInventoryItems).toHaveBeenLastCalledWith(expect.objectContaining({ query: 'CAT6', page: 1 })))
  })
  it('新建库存校验必填单位，提交真实分单位金额', async () => {
    const repo = repository()
    render(<InventoryWorkspace repository={repo} />)
    await screen.findByRole('button', { name: '网线' })
    fireEvent.click(screen.getByRole('button', { name: /新增库存/ }))
    const dialog = await screen.findByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('物料名称'), { target: { value: '交换机' } })
    fireEvent.change(within(dialog).getByLabelText('计量单位'), { target: { value: '台' } })
    fireEvent.change(within(dialog).getByLabelText('期初数量'), { target: { value: '2.500' } })
    fireEvent.change(within(dialog).getByLabelText('期初成本单价（元）'), { target: { value: '12.34' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /保.*存/ }))
    await waitFor(() => expect(repo.createInventoryItem).toHaveBeenCalledWith(expect.objectContaining({ name: '交换机', unit: '台', opening_quantity: '2.500', opening_unit_cost_cents: 1234 })))
  })
  it('库存调整冲销确认后携带原调整版本与原因', async () => {
    const repo = repository()
    const movement = { id: 4, inventory_item_id: 1, project_id: null, procurement_line_id: null, movement_type: 'adjustment' as const, quantity_delta: '2.000', value_delta_cents: 600, quantity_after: '12.000', value_after_cents: 3600, source_type: 'inventory_adjustment', source_id: 12, occurred_on: '2026-10-06', reason: '盘盈', created_at: '', adjustment_status: 'active' as const, adjustment_revision: 3 }
    repo.getInventoryItem = async () => ({ source: 'live', data: { ...item, movements: [movement] } })
    repo.listInventoryMovements = async () => ({ source: 'live', data: { items: [movement], total: 1, page: 1, page_size: 20 } })
    repo.reverseInventoryAdjustment = vi.fn<InventoryHttpRepository['reverseInventoryAdjustment']>().mockResolvedValue({ source: 'live', data: { id: 12, inventory_item_id: 1, quantity_delta: '2.000', unit_cost_cents: 300, reason: '盘盈', occurred_on: '2026-10-06', value_delta_cents: 600, status: 'reversed', revision: 4, reversal_reason: '重复盘点', reversed_at: '2026-10-06', movement, reversal_movement: null, created_at: '' } })
    repo.discardReverseInventoryAdjustment = () => true
    render(<InventoryWorkspace repository={repo} />)
    fireEvent.click(await screen.findByRole('button', { name: '网线' }))
    fireEvent.click(await screen.findByRole('button', { name: '冲销调整' }))
    const dialogs = screen.getAllByRole('dialog')
    const dialog = dialogs[dialogs.length - 1]!
    fireEvent.change(within(dialog).getByLabelText('冲销原因'), { target: { value: '重复盘点' } })
    fireEvent.click(within(dialog).getByRole('button', { name: /^保\s*存$/ }))
    const confirmation = await screen.findByRole('button', { name: '确认冲销' })
    expect(repo.reverseInventoryAdjustment).not.toHaveBeenCalled()
    fireEvent.click(confirmation)
    await waitFor(() => expect(repo.reverseInventoryAdjustment).toHaveBeenCalledWith(12, { reason: '重复盘点', expected_revision: 3 }))
  })
})
